### ISSUE TITLE
安装1.13.1-cp37-cu118.whl

### ISSUE THREAD

**Issue by BroenLin** [Qsingle/MegEngine_CU11#4]
您好，从百度网盘下载了MegEngine-1.13.1-cp37-cu118.whl。
我的设备是windows，RTX3060，CUDA11.8；环境是python3.7.16
但是安装了whl文件后，无法连接GPU，
但是import megengine as mge; mge.get_device_count("gpu")的结果为1

>>> import megengine as mg
>>> mg.set_default_device(device='gpu0')
>>> M.Conv2d(3, 64, kernel_size=7, stride=2, padding=3)
debug: failed to load cuda func: cuDeviceGetNvSciSyncAttributes.(May caused by currently driver is too old,
if you find cuda is not available(by import megengine as mge; mge.get_device_count("gpu")
or find some inexplicable crash of the program,
try upgrade driver from https://developer.nvidia.com/cuda-downloads)
31 14:50:00[mgb] WRN [dnn]
            Cudnn8 will jit ptx code with cache. You can set
            CUDA_CACHE_MAXSIZE and CUDA_CACHE_PATH environment var to avoid repeat jit(very slow).
            For example `export CUDA_CACHE_MAXSIZE=2147483647` and `export CUDA_CACHE_PATH=/data/.cuda_cache`
Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3))
>>>

**Comment by BroenLin** [comment]
请问是可以直接安装whl还是得先按readme.md执行steps

**Comment by Qsingle** [comment]
可以直接安装whl
---- 回复的原邮件 ----
发件人 ***@***.***> 日期 2024年07月31日 17:19 收件人 ***@***.***> 抄送至 ***@***.***> 主题 Re: [Qsingle/MegEngine_CU11] 安装1.13.1-cp37-cu118.whl (Issue #4) 
请问是可以直接安装whl还是得先按readme.md执行steps

**Comment by BroenLin** [comment]
> 可以直接安装whl ---- 回复的原邮件 ---- 发件人 ***@***.***> 日期 2024年07月31日 17:19 收件人 ***@***.***> 抄送至 ***@***.***> 主题 Re: [Qsingle/MegEngine_CU11] 安装1.13.1-cp37-cu118.whl (Issue #4) 请问是可以直接安装whl还是得先按readme.md执行steps — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

好的，感谢
